version: 2
registries:
  fabric:
    url: "https://maven.fabricmc.net/"
    type: maven-repository
  dark-matter:
    url: "https://maven.pkg.github.com/constellation-mc/dark-matter"
    type: maven-repository
  gradle-plugins:
    url: "https://plugins.gradle.org/m2/"
    type: maven-repository
  maven-central:
    url: "https://repo1.maven.org/maven2/"
    type: maven-repository

updates:
  - package-ecosystem: gradle
    registries: *
    directory: /
    schedule:
      interval: daily